BASE_URL = '/assets/icons/banks/'
BANK_IMAGE_URL_DICT = {
'씨티은행' : BASE_URL+'citi-logo.svg',
'대구은행' : BASE_URL+'daegoo-logo.svg',
'국민은행' : BASE_URL+'gookmin-logo.svg',
'광주은행' : BASE_URL+'gwangju-logo.svg',
'경남은행' : BASE_URL+'gyungnam-logo.svg',
'하나은행' : BASE_URL+'hana-logo.svg',
'중소기업은행' : BASE_URL+'ibk-logo.svg',
'제주은행' : BASE_URL+'jeju-logo.svg',
'전북은행' : BASE_URL+'jeonbook-logo.svg',
'주식회사 카카오뱅크' : BASE_URL+'kakaobank-logo.svg',
'주식회사 케이뱅크' : BASE_URL+'kbank-logo.svg',
'한국산업은행' : BASE_URL+'kdb-logo.svg',
'한국은행' : BASE_URL+'korea-logo.svg',
'농협은행주식회사' : BASE_URL+'nh-logo.svg',
'우체국' : BASE_URL+'postoffice-logo.svg',
'신한은행' : BASE_URL+'shinhan-logo.svg',
'수협은행' : BASE_URL+'soohyeop-logo.svg',
'토스뱅크 주식회사' : BASE_URL+'tossbank-logo.svg',
'우리은행' : BASE_URL+'woori-logo.svg',
}