# Generated by Django 4.2.6 on 2024-05-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savedata', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='annuity',
            field=models.ManyToManyField(related_name='like_annuity', to='savedata.annuityproducts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='creditloan',
            field=models.ManyToManyField(related_name='like_creditloan', to='savedata.creditloanproducts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='product',
            field=models.ManyToManyField(related_name='like_product', to='savedata.depositproducts'),
        ),
    ]
