# Generated by Django 4.2.6 on 2024-05-23 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnuityProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(default=None)),
                ('kor_co_nm', models.TextField(default=None)),
                ('fin_co_no', models.TextField(default=None)),
                ('fin_prdt_nm', models.TextField(default=None)),
                ('etc', models.TextField(blank=True, default='기타사항 없음')),
                ('join_way', models.TextField(blank=True, default='정보 없음')),
                ('pnsn_kind_nm', models.TextField(blank=True, default='정보 없음')),
                ('mntn_cnt', models.IntegerField(blank=True, default=0)),
                ('prdt_type_nm', models.TextField(default=None)),
                ('dcls_rate', models.FloatField(default=None)),
                ('guar_rate', models.TextField(blank=True, default=0)),
                ('btrm_prft_rate_1', models.FloatField(blank=True, default=0)),
                ('btrm_prft_rate_2', models.FloatField(blank=True, default=0)),
                ('sale_co', models.TextField(blank=True, default='정보 없음')),
                ('dcls_strt_day', models.DateField(blank=True)),
                ('dcls_end_day', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='creditLoanProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(default=None)),
                ('kor_co_nm', models.TextField(default=None)),
                ('fin_co_no', models.TextField(default=None)),
                ('fin_prdt_nm', models.TextField(default=None)),
                ('join_way', models.TextField(blank=True, default='정보 없음')),
                ('crdt_prdt_type', models.IntegerField(default=None)),
                ('crdt_prdt_type_nm', models.TextField(default=None)),
                ('cb_name', models.TextField(blank=True, default='정보 없음')),
                ('dcls_strt_day', models.DateField(blank=True)),
                ('dcls_end_day', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(default=None)),
                ('kor_co_nm', models.TextField(default=None)),
                ('fin_co_no', models.TextField(default=None)),
                ('fin_prdt_nm', models.TextField(default=None)),
                ('etc_note', models.TextField(blank=True, default='정보 없음')),
                ('join_deny', models.IntegerField(blank=True, default=4)),
                ('join_member', models.TextField(blank=True, default='정보 없음')),
                ('join_way', models.TextField(blank=True, default='정보 없음')),
                ('spcl_cnd', models.TextField(blank=True, default='우대조건 없음')),
                ('product_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DepositOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(default=None)),
                ('fin_co_no', models.TextField(default=None)),
                ('intr_rate_type_nm', models.CharField(default=None, max_length=100)),
                ('intr_rate', models.FloatField(default=None)),
                ('intr_rate2', models.FloatField(default=None)),
                ('save_trm', models.IntegerField(default=None)),
                ('rsrv_type_nm', models.TextField(default=None, null=True)),
                ('rsrv_type', models.TextField(default=None, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_option', to='savedata.depositproducts')),
            ],
        ),
        migrations.CreateModel(
            name='creditLoanOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(default=None)),
                ('fin_co_no', models.TextField(default=None)),
                ('crdt_lend_rate_type', models.TextField(default=None)),
                ('crdt_lend_rate_type_nm', models.TextField(default=None)),
                ('crdt_grad_1', models.FloatField(default=0)),
                ('crdt_grad_4', models.FloatField(default=0)),
                ('crdt_grad_5', models.FloatField(default=0)),
                ('crdt_grad_6', models.FloatField(default=0)),
                ('crdt_grad_10', models.FloatField(default=0)),
                ('crdt_grad_11', models.FloatField(default=0)),
                ('crdt_grad_12', models.FloatField(default=0)),
                ('crdt_grad_13', models.FloatField(default=0)),
                ('crdt_grad_avg', models.FloatField(default=None)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditLoan_option', to='savedata.creditloanproducts')),
            ],
        ),
        migrations.CreateModel(
            name='AnnuityOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(default=None)),
                ('fin_co_no', models.TextField(default=None)),
                ('pnsn_recp_trm', models.TextField(default=None)),
                ('pnsn_entr_age', models.IntegerField(default=None)),
                ('mon_paym_atm', models.IntegerField(default=None)),
                ('paym_prd', models.IntegerField(default=None)),
                ('pnsn_strt_age', models.IntegerField(default=None)),
                ('pnsn_recp_amt', models.IntegerField(blank=True, default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annuity_option', to='savedata.annuityproducts')),
            ],
        ),
    ]
