# Generated by Django 4.2.11 on 2024-05-14 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnuityProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(default='')),
                ('kor_co_nm', models.TextField(default='')),
                ('fin_prdt_nm', models.TextField(default='')),
                ('etc', models.TextField(default='')),
                ('join_way', models.TextField(default='')),
                ('pnsn_kind_nm', models.TextField(default='')),
                ('mntn_cnt', models.IntegerField(default=0)),
                ('prdt_type_nm', models.TextField(default='')),
                ('dcls_rate', models.FloatField(default=0)),
                ('guar_rate', models.FloatField(default=0)),
                ('btrm_prft_rate_1', models.FloatField(default=0)),
                ('btrm_prft_rate_2', models.FloatField(default=0)),
                ('sale_co', models.TextField(default='')),
                ('dcls_strt_day', models.DateTimeField()),
                ('dcls_end_day', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='creditLoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(default='')),
                ('kor_co_nm', models.TextField(default='')),
                ('fin_prdt_nm', models.TextField(default='')),
                ('join_way', models.TextField(default='')),
                ('crdt_prdt_type', models.IntegerField(default=0)),
                ('crdt_prdt_type_nm', models.TextField(default='')),
                ('cb_name', models.TextField(default='')),
                ('dcls_strt_day', models.DateTimeField()),
                ('dcls_end_day', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DepositProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(default='')),
                ('kor_co_nm', models.TextField(default='')),
                ('fin_prdt_nm', models.TextField(default='')),
                ('etc_note', models.TextField(default='')),
                ('join_deny', models.IntegerField(default=-1)),
                ('join_member', models.TextField(default='')),
                ('join_way', models.TextField(default='')),
                ('spcl_cnd', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(default='')),
                ('kor_co_nm', models.TextField(default='')),
                ('fin_prdt_nm', models.TextField(default='')),
                ('etc_note', models.TextField(default='')),
                ('join_deny', models.IntegerField(default=-1)),
                ('join_member', models.TextField(default='')),
                ('join_way', models.TextField(default='')),
                ('spcl_cnd', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(default='')),
                ('intr_rate_type_nm', models.CharField(default='', max_length=100)),
                ('intr_rate', models.FloatField(default=0, null=True)),
                ('intr_rate2', models.FloatField(default=0)),
                ('save_trm', models.IntegerField(default=0)),
                ('rsrv_type', models.TextField(default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_option', to='savedata.installmentproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DepositOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(default='')),
                ('intr_rate_type_nm', models.CharField(default='', max_length=100)),
                ('intr_rate', models.FloatField(default=0, null=True)),
                ('intr_rate2', models.FloatField(default=0)),
                ('save_trm', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_option', to='savedata.depositproducts')),
            ],
        ),
        migrations.CreateModel(
            name='creditLoanOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crdt_lend_rate_type', models.TextField(default='')),
                ('crdt_lend_rate_type_nm', models.TextField(default='')),
                ('crdt_grad_1', models.FloatField(default=0)),
                ('crdt_grad_4', models.FloatField(default=0)),
                ('crdt_grad_5', models.FloatField(default=0)),
                ('crdt_grad_6', models.FloatField(default=0)),
                ('crdt_grad_10', models.FloatField(default=0)),
                ('crdt_grad_11', models.FloatField(default=0)),
                ('crdt_grad_12', models.FloatField(default=0)),
                ('crdt_grad_13', models.FloatField(default=0)),
                ('crdt_grad_avg', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annuity_option', to='savedata.creditloanproduct')),
            ],
        ),
        migrations.CreateModel(
            name='AnnuityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(default='')),
                ('pnsn_recp_trm', models.TextField(default='')),
                ('pnsn_entr_age', models.IntegerField(default=0)),
                ('mon_paym_atm', models.IntegerField(default=0)),
                ('paym_prd', models.IntegerField(default=0)),
                ('pnsn_strt_age', models.IntegerField(default=0)),
                ('pnsn_recp_amt', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annuity_option', to='savedata.annuityproduct')),
            ],
        ),
    ]
