# Generated by Django 4.2.11 on 2024-05-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annuityproducts',
            name='dcls_end_day',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='annuityproducts',
            name='dcls_strt_day',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='creditloanproducts',
            name='dcls_end_day',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='creditloanproducts',
            name='dcls_strt_day',
            field=models.DateField(blank=True),
        ),
    ]
