# Generated by Django 4.2.11 on 2024-05-17 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditloanoptions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditLoan_option', to='savedata.creditloanproducts'),
        ),
    ]
