# Generated by Django 4.2.11 on 2024-05-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savedata', '0002_alter_annuityproducts_dcls_end_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annuityproducts',
            name='dcls_end_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
