# Generated by Django 4.2.11 on 2024-05-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savedata', '0003_alter_annuityproducts_dcls_end_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annuityproducts',
            name='guar_rate',
            field=models.TextField(blank=True, default=0),
        ),
    ]
